import { v4 as uuidv4 } from 'uuid';

export const initialPosts = [
    {
        id: uuidv4(),
        title: "Understanding React Hooks",
        author: "Alex Johnson",
        content: "Hooks are functions that let you 'hook into' React state and lifecycle features from function components. The most common ones are useState and useEffect. They drastically simplify state management.",
        tags: ["react", "hooks", "frontend"],
        createdAt: "2025-07-01T10:00:00Z",
        updatedAt: "2025-07-01T10:00:00Z",
    },
    {
        id: uuidv4(),
        title: "Introduction to Bootstrap 5 Grid System",
        author: "Emily Clark",
        content: "Bootstrap's grid system is built with Flexbox and is fully responsive. It allows up to 12 columns across a page and supports breakpoints for different screen sizes (sm, md, lg, xl, xxl).",
        tags: ["bootstrap", "css", "responsive"],
        createdAt: "2025-07-03T14:30:00Z",
        updatedAt: "2025-07-03T14:30:00Z",
    },
    {
        id: uuidv4(),
        title: "State Management with Context API",
        author: "Alex Johnson",
        content: "The Context API provides a way to pass data through the component tree without having to pass props down manually at every level. It's excellent for global state like user authentication or theme settings.",
        tags: ["react", "context", "state"],
        createdAt: "2025-07-05T09:15:00Z",
        updatedAt: "2025-07-05T09:15:00Z",
    },
    {
        id: uuidv4(),
        title: "What is CRUD?",
        author: "Piyush",
        content: "CRUD stands for Create, Read, Update, and Delete. These are the four basic functions of persistent storage.",
        tags: ["basics", "database"],
        createdAt: "2025-07-05T12:00:00Z",
        updatedAt: "2025-07-05T12:00:00Z",
    },
    // Add 6 more posts here for a total of 10+
    {
        id: uuidv4(),
        title: "Effective CSS Variable Usage",
        author: "Emily Clark",
        content: "CSS variables, or custom properties, allow you to define values once and reuse them in multiple places. This makes themes and general styling much easier to manage.",
        tags: ["css", "styling"],
        createdAt: "2025-07-06T11:00:00Z",
        updatedAt: "2025-07-06T11:00:00Z",
    },
    {
        id: uuidv4(),
        title: "React Router DOM v6 Basics",
        author: "John Smith",
        content: "React Router DOM v6 introduced significant changes, including the `useRoutes` hook and improved nested routing structure using `<Outlet />`.",
        tags: ["react", "routing"],
        createdAt: "2025-07-07T15:00:00Z",
        updatedAt: "2025-07-07T15:00:00Z",
    },
    {
        id: uuidv4(),
        title: "Vite vs CRA: A Comparison",
        author: "Jane Doe",
        content: "Vite offers a much faster dev server startup and hot module replacement due to its use of native ES modules. CRA is older, more established, but slower for large projects.",
        tags: ["tools", "performance"],
        createdAt: "2025-07-08T09:00:00Z",
        updatedAt: "2025-07-08T09:00:00Z",
    },
    {
        id: uuidv4(),
        title: "Tips for Clean Component Structure",
        author: "Piyush",
        content: "Keep components small, focus on a single responsibility, and use custom hooks to abstract complex logic away from the UI.",
        tags: ["architecture", "react"],
        createdAt: "2025-07-09T17:00:00Z",
        updatedAt: "2025-07-09T17:00:00Z",
    },
    {
        id: uuidv4(),
        title: "Accessibility in Frontend Development",
        author: "Alex Johnson",
        content: "Ensure proper use of semantic HTML, provide alt text for images, and test keyboard navigation to make your application usable by everyone.",
        tags: ["accessibility", "ui"],
        createdAt: "2025-07-10T11:30:00Z",
        updatedAt: "2025-07-10T11:30:00Z",
    },
    {
        id: uuidv4(),
        title: "Using `useEffect` for Data Fetching",
        author: "John Smith",
        content: "The `useEffect` hook is the primary tool for side effects in React, including fetching data. Remember to include dependencies and handle cleanup.",
        tags: ["react", "hooks"],
        createdAt: "2025-07-11T16:00:00Z",
        updatedAt: "2025-07-11T16:00:00Z",
    },
];